Settings:
  mysql: false  
  path-2-sqllitedb: 'jdbc:sqlite:plugins/VoteRanks/VoteRanks.db'
  mysql-user: 'VoteRanks'
  mysql-password: 'VoteRanks'
  mysql-database-url: 'jdbc:mysql://localhost:3306/VoteRanks'
  debug-mode: false
  broadcast-rank-change: true
  use-sidebar-4-votelist: true  
  use-chat-4-votelist: false
  use-chat-4-votes: false
  use-sidebar-4-votes: true
  show-votes-on-tab: false
  sidebar-show-time-seconds: 10
  auto-db-reset: false
  auto-db-reset-time-days: 30 
  command_vote: true
  firstjoined-book: false
  firstjoined-path: plugins\VoteRanks\Books\fjoin.txt
  timer: 20
  show-no-permission-msg: true
  backup-on-delete: true
  backup-top-x: 20
Messages:
  config-saved: '&a[&6VoteRanks&a] &6Config&a saved! '
  rank-change-msg: '&a[&6VoteRanks&a] &6<player> &a went up a ranking vote! (<rank>)'
  rank-change-msg: '&a[&6VoteRanks&a] &6<player> &a went up a ranking vote! (<rank>)'
  votelist-header: '&4--- The &6<size> &4best voters! ---'
  votelist-place-format: '&a[&6VoteRanks&a] &6Rank: <rank>, Player <player> with <votes> votes!'
  votes-see-format-more-than-one: '&a[&6VoteRanks&a] &aYou are place <rank> with <votes> votes including <same rank> other players!'
  votes-see-format: '&a[&6VoteRanks&a] &aYou are place <rank> with <votes> votes!'
  votes-see-format-others: '&a[&6VoteRanks&a] &a<player> has place <rank> with <votes> votes!'
  votes-see-format-others-more-than-one: '&a[&6VoteRanks&a] &a<player> has place <rank> with <votes> votes including <same rank> other player!'
  votes-player-not-found: '&a[&6VoteRanks&a] &4<player> was not found!'
  setvotes-not-int: '&a[&6VoteRanks&a] &4Please add a number!'
  setvotes-2less-para: '&a[&6VoteRanks&a] &4/setvotes Player Amount'
  setvotes-success: '&a[&6VoteRanks&a] &a<player> has now <votes> votes!'
  clearvotes-sure: '&a[&6VoteRanks&a] &a Are you sure to do that?'
  clearvotes-deny: '&a[&6VoteRanks&a] &a Clearing aborted!'
  clearvotes-working: '&a[&6VoteRanks&a] &aDeleting all database-records ...'
  clearvotes-done: '&a[&6VoteRanks&a] &aAll records deleted!'  
  sidebar-votelist-header: '&4The &6<size> &4best voters!'
  sidebar-rank-name: '&6Rank:'
  sidebar-votes-name: '&6Votes:'
  sidebar-same-rank-name: '&6Other User:'
  no-permissions: '&4You are not permitted to use <command>'
  player-not-found: '&4<player> not found'
  item-stored: '&7Item with the &c<id>&7 stored in the database'
  goal-message-added: '&a[&6VoteRanks&a] Private Message <message> added to goal with id <id>, remember to use editgoal save to save!'
  goal-dbitem-added: '&a[&6VoteRanks&a] DbItem with the id <dbid> added to goal with id <id>, remember to use editgoal save to save!'
  goal-book-added: '&a[&6VoteRanks&a] Book with Path <path> added to goal with id <id>, remember to use editgoal save to save!'
  goal-book-not-found: '&a[&6VoteRanks&a] The Book with Path <path> does not exist!, remember to use editgoal save to save!'
  goal-broadcast-added: '&a[&6VoteRanks&a] Broadcast <broadcast> added to goal with id <id>, remember to use editgoal save to save!'
  goal-randomitemlist-added: '&a[&6VoteRanks&a] Random Item List named <list> added to goal with id <id>, remember to use editgoal save to save!'
  goal-randomcommandlist-added: '&a[&6VoteRanks&a] Random Command List named <list> added to goal with id <id>, remember to use editgoal save to save!'
  goal-command-added: '&a[&6VoteRanks&a] Command <command> added to goal with id <id>, remember to use editgoal save to save!'
  goal-list-not-existing: '&a[&6VoteRanks&a] Warning: List <list> does not exist, remember to use editgoal save to save!'
  goal-message-set: '&a[&6VoteRanks&a] Private Message <message> set to goal with id <id> and message with id <mid>, remember to use editgoal save to save!'
  goal-dbitem-set: '&a[&6VoteRanks&a] DbItem with the id <dbid> set to goal with id <id> and the countID <dbicnid>, remember to use editgoal save to save!'
  goal-book-set: '&a[&6VoteRanks&a] Book with Path <path> set to goal with id <id> and Book ID <bid>, remember to use editgoal save to save!'
  goal-broadcast-set: '&a[&6VoteRanks&a] Broadcast <broadcast> set to goal with id <id> and BroadcastID <bid>, remember to use editgoal save to save!'
  goal-randomitemlist-set: '&a[&6VoteRanks&a] Random Item List named <list> set to goal with id <id> and the ListID <list>, remember to use editgoal save to save!'
  goal-randomcommandlist-set: '&a[&6VoteRanks&a] Random Command List named <list> set to goal with id <id> and the ListID <list>, remember to use editgoal save to save!'
  goal-command-set: '&a[&6VoteRanks&a] Command <command> set to goal with id <id> and the CiD <cid>, remember to use editgoal save to save!'
  goal-message-removed: '&a[&6VoteRanks&a] Private Message <message> removed from goal with id <id>, remember to use editgoal save to save!'
  goal-dbitem-removed: '&a[&6VoteRanks&a] DbItem with the id <dbid> removed from goal with id <id> and the countID <dbicnid>, remember to use editgoal save to save!'
  goal-book-removed: '&a[&6VoteRanks&a] Book with Path <path> removed from goal with id <id> and Book ID <bid>, remember to use editgoal save to save!'
  goal-broadcast-removed: '&a[&6VoteRanks&a] Broadcast <broadcast> removed from goal with id <id> and BroadcastID <bid>, remember to use editgoal save to save!'
  goal-randomitemlist-removed: '&a[&6VoteRanks&a] Random Item List named <list> removed from goal with id <id> and the ListID <list>, remember to use editgoal save to save!'
  goal-randomcommandlist-removed: '&a[&6VoteRanks&a] Random Command List named <list> removed from goal with id <id> and the ListID <list>, remember to use editgoal save to save!'
  goal-command-removed: '&a[&6VoteRanks&a] Command <command> removed from goal with id <id> and the CiD <cid>, remember to use editgoal save to save!'
  goal-list-not-existing: '&a[&6VoteRanks&a] Warning: List <list> does not exist'
  not-a-number: '&a[&6VoteRanks&a] <string> is not a number!'  
  out-of-range: '&a[&6VoteRanks&a] <number> is out of range (max value is <max>!)'  
  editgoal-types: '&a[&6VoteRanks&a] Following Subcommands of editgoal can be used<newline>save<newline>show <opt: goal ID><newline>addmessage <goalid> <message><newline>addbroadcast <goalid> <broadcast><newline>addcommand <goalid> <command><newline>addGiveList <goalid> <list><newline>addCommandList <goalid> <list><newline>addBook <goalid> <path><newline>setmessage <goalid> <message><newline>setbroadcast <goalid> <broadcast><newline>setcommand <goalid> <command><newline>setGiveList <goalid> <list><newline>setCommandList <goalid> <list><newline>setBook <goalid> <path><newline>removemessage <goalid> <message><newline>removebroadcast <goalid> <broadcast><newline>removecommand <goalid> <command><newline>removeGiveList <goalid> <list><newline>removeCommandList <goalid> <list><newline>removeBook <goalid> <path>'
  goal-neededVotes: '&a[&6VoteRanks&a] Needed votes <type> <votes>'
  goal-messages: '&a[&6VoteRanks&a] Messages:'
  goal-commands: '&a[&6VoteRanks&a] Commands:'
  goal-broadcast: '&a[&6VoteRanks&a] Broadcasts:'
  goal-books: '&a[&6VoteRanks&a] Books:'
  goal-items: '&a[&6VoteRanks&a] Items:'
Goals:
  - 'votes=1;Message=Your first vote!;broadcast=<player> has 1 vote;Give=DIAMOND,1,null,-1,null,-1,-1,-1;giveDb=1'
  - 'votes=10;Message=10 votes! well-done!;broadcast=<player> has 10 votes'
  - 'votes=50;Message=Keep it up and you will be vote-king!;broadcast=<player> has 50 votes'
  - 'votes=100;Message=Good-work,from now on you are unofficial vote-king!;broadcast=<player> has 100 votes'
votesits:
  - '[BLUE]http://www.minecraft-serverlist.eu/'
  - '[BLUE]http://www.minecraft-serverlist.net/serverlist'
  - '[BLUE]http://serverliste.me/'
randomitemlist:
  - DIAMOND,1,null,-1,null,-1,-1,-1
  - LEATHER_LEGGINGS,1,PROTECTION_EXPLOSIONS,1337,&6Marius-Suit,50,0,0
randomcommandlist:
  - 'say <player> has voted'